version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    volumes:
      - .:/app
      - ./.secret:/app/.secret
    ports:
      - "8000:8000"
    depends_on:
      - db

  # PostgreSQL Database
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_DB: assessment_db
      POSTGRES_USER: AB_user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
